// SPORTEX Product Data — READ ONLY
// ⚠️ DO NOT edit this file directly
// All data is managed via CMS: https://sportexproduction.com/admin/
// Changes sync automatically: CMS → GitHub → Cloudflare → Frontend

const PLACEHOLDER = 'images/placeholder.svg';
const RAW_PREFIX = 'https://raw.githubusercontent.com/ahrilove1/sportex/main/';
// Convert GitHub raw URLs to local paths for Cloudflare CDN + caching
function cdn(src) {
  return (src||'').startsWith(RAW_PREFIX) ? (src||'').slice(RAW_PREFIX.length) : (src||'');
}

let allProducts = [];
let productsLoaded = (async () => {
  try {
    const r = await fetch('data/products.json');
    const data = await r.json();
    // Transform CMS format to site format + apply placeholder for empty images
    allProducts = (data.products_list || []).map(p => ({
      ...p,
      thumbnail: cdn(p.thumbnail) || PLACEHOLDER,
      images: (p.images || []).map(i => typeof i === 'string' ? cdn(i) : cdn(i.url || i.image || '')).filter(u => u),
      features: (p.features || []).map(f => typeof f === 'string' ? f : (f.text || f.feature || '')),
    }));
    // If all gallery images are empty, use placeholder
    allProducts.forEach(p => { if (!p.images.length) p.images = [PLACEHOLDER]; });
  } catch (e) {
    console.error('Failed to load products data', e);
  }
})();

// 按品类获取产品
function getProductsByCategory(cat) {
  return allProducts.filter(p => p.category === cat);
}

// 按ID获取产品
function getProductById(id) {
  return allProducts.find(p => p.id === id);
}

// Helper: img tag with responsive size hints + CDN URL + lazy + async decode
function imgTag(src, alt, cls, hint) {
  var url = cdn(src || PLACEHOLDER);
  var sizes = hint === 'card' ? '(max-width:640px) 50vw, 300px' :
              hint === 'gallery' ? '(max-width:640px) 100vw, 600px' :
              hint === 'detail' ? '(max-width:640px) 100vw, 1200px' :
              '(max-width:640px) 50vw, 300px';
  return '<img src="' + url + '" alt="' + (alt || '') + '" sizes="' + sizes + '" decoding="async" onerror="this.onerror=null;this.src=\'' + PLACEHOLDER + '\'"' + (cls ? ' class="' + cls + '"' : '') + ' loading="lazy">';
}
