// SPORTEX Product Data — READ ONLY
// ⚠️ DO NOT edit this file directly
// All data is managed via CMS: https://sportexproduction.com/admin/
// Changes sync automatically: CMS → GitHub → Cloudflare → Frontend

const PLACEHOLDER = 'images/placeholder.svg';
const RAW_PREFIX = 'https://raw.githubusercontent.com/ahrilove1/sportex/main/';
// Convert GitHub raw URLs to local paths for Cloudflare CDN + caching
function cdn(src) {
  return (src||'').startsWith(RAW_PREFIX) ? (src||'').slice(RAW_PREFIX.length) : (src||'');
}

// Smart fetch: try KV first (instant), fallback to static file
async function fetchData(name) {
  try {
    var r = await fetch('/api/data/' + name);
    if (r.ok) { var d = await r.json(); if (Object.keys(d).length) return d; }
  } catch(e){}
  var r = await fetch('data/' + name + '.json');
  return await r.json();
}

let allProducts = [];
// Build thumb lookup from images.json (KV or local)
window._imageThumbs = {};
(async () => {
  try { var idata = await fetchData('images'); (idata.images||[]).forEach(function(i){ if(i.thumb) window._imageThumbs[i.path] = i.thumb; }); } catch(e){}
})();
let productsLoaded = (async () => {
  try {
    const data = await fetchData('products');
    // Transform CMS format to site format + apply placeholder for empty images
    allProducts = (data.products_list || []).map(p => ({
      ...p,
      thumbnail: cdn(p.thumbnail) || PLACEHOLDER,
      images: (p.images || []).map(i => typeof i === 'string' ? cdn(i) : cdn(i.url || i.image || '')).filter(u => u),
      features: (p.features || []).map(f => typeof f === 'string' ? f : (f.text || f.feature || '')),
    }));
    // If all gallery images are empty, use placeholder
    allProducts.forEach(p => { if (!p.images.length) p.images = [PLACEHOLDER]; });
  } catch (e) {
    console.error('Failed to load products data', e);
  }
})();

// 按品类获取产品
function getProductsByCategory(cat) {
  return allProducts.filter(p => p.category === cat);
}

// 按子品类筛选 (shirts / pants / other)
function filterBySubcat(products, subcat) {
  return products.filter(function(p) {
    var name = (p.name||'').toLowerCase();
    var tags = (p.tags||'').toLowerCase();
    if (subcat === 'shirts') return /shirt|polo|windbreaker|jacket|top/.test(name) || /shirt/.test(tags) || /shirts/.test(tags);
    if (subcat === 'pants') return /pants|trouser|chino|short|cargo|jean/.test(name) || /pants/.test(tags);
    return true;
  });
}

// 按ID获取产品
function getProductById(id) {
  return allProducts.find(p => p.id === id);
}

// Helper: img tag with srcset (thumb + full) for optimized loading
function imgTag(src, alt, cls, hint) {
  var url = cdn(src || PLACEHOLDER);
  var thumb = url;
  // Look up thumb from image registry if available
  if (window._imageThumbs && window._imageThumbs[url]) thumb = window._imageThumbs[url];
  var sizes = hint === 'card' ? '(max-width:640px) 50vw, 300px' : hint === 'gallery' ? '(max-width:640px) 100vw, 600px' : hint === 'detail' ? '(max-width:640px) 100vw, 1200px' : '(max-width:640px) 50vw, 300px';
  var srcset = thumb !== url ? thumb + ' 400w, ' + url + ' 1200w' : '';
  return '<img src="' + url + '"' + (srcset ? ' srcset="' + srcset + '" sizes="' + sizes + '"' : ' sizes="' + sizes + '"') + ' alt="' + (alt || '') + '" decoding="async" onerror="this.onerror=null;this.src=\'' + PLACEHOLDER + '\'"' + (cls ? ' class="' + cls + '"' : '') + ' loading="lazy">';
}
